// <auto-generated />
using System;
using FacebookAutoPost.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FacebookAutoPost.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("FacebookAutoPost.Models.AutoPost", b =>
                {
                    b.Property<string>("PageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostTemplate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uri")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAPI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PageId");

                    b.ToTable("AutoPosts");
                });

            modelBuilder.Entity("FacebookAutoPost.Models.Frequency", b =>
                {
                    b.Property<string>("PageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cron")
                        .HasColumnType("TEXT");

                    b.Property<string>("Freaquency")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRandom")
                        .HasColumnType("INTEGER");

                    b.HasKey("PageId");

                    b.ToTable("Frequency");
                });

            modelBuilder.Entity("FacebookAutoPost.Models.ParamsUri", b =>
                {
                    b.Property<string>("PageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamOne")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamThree")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamTwo")
                        .HasColumnType("TEXT");

                    b.HasKey("PageId");

                    b.ToTable("ParamsUri");
                });
#pragma warning restore 612, 618
        }
    }
}
